[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dummy_package"
version = "0.0.1"
description = "A dummy package for testing Cloudsmith upload"
readme = "README.md"
authors = [
  { name = "Somya Lavania", email = "somyalavania3@gmail.com" }
]
license = { text = "MIT" }
requires-python = ">=3.8"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3"
]
