[project]
name = "dummy_package"   # ✅ use underscore, since filename has it
version = "0.1.0"
description = "A dummy package for testing Cloudsmith upload"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Somya Lavania", email = "somyalavania3@gmail.com" }]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

