name: Build Python Package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show repo layout
        run: |
          pwd
          ls -R

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build setuptools wheel

      - name: Show pyproject.toml
        run: |
          if [ -f pyproject.toml ]; then
            echo "===== pyproject.toml ====="
            cat pyproject.toml
            echo "=========================="
          else
            echo "pyproject.toml not found" && exit 1
          fi

      - name: Build package
        run: python -m build -s -w

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/
          if-no-files-found: error
