name: Promote Python Package

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: "Package version to promote (e.g., 0.1.0)"
        required: true
        type: string

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: "staging"         # staging → production
  CLOUDSMITH_PRODUCTION_REPO: "production"
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}
  PACKAGE_NAME: "example-package"             # PEP 503 normalized name; change if different

permissions:
  contents: read
  id-token: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudsmith CLI (OIDC)
        uses: cloudsmith-io/cloudsmith-cli-action@v1
        with:
          oidc: true
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      - name: Promote from staging → production (copy, non-destructive)
        run: |
          cloudsmith copy \
            "${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}" \
            "${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_PRODUCTION_REPO }}" \
            --package="${{ env.PACKAGE_NAME }}" \
            --version="${{ inputs.package_version }}" \
            --yes
