name: Promote Python Package

on:
  repository_dispatch:
    types: [package_synchronised]   # Triggered by Cloudsmith webhook

permissions:
  contents: read
  id-token: write    # Required for OIDC
  actions: read

env:
  CS_NAMESPACE: ${{ secrets.CS_NAMESPACE }}
  CS_STAGING_REPO: "staging"
  CS_PROD_REPO: "production"

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Cloudsmith (OIDC)
        uses: cloudsmith-io/cloudsmith-cli-action@v1
        with:
          oidc-namespace: ${{ secrets.CS_OIDC_NAMESPACE }}
          oidc-service-slug: ${{ secrets.CS_OIDC_SERVICE_SLUG }}
          install-cli: 'true'

      - name: Verify Cloudsmith authentication
        run: cloudsmith whoami

      - name: Tag package from webhook payload
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "Received payload: $PAYLOAD"
          pkg_name=$(echo $PAYLOAD | jq -r '.package_name // empty')
          pkg_version=$(echo $PAYLOAD | jq -r '.package_version // empty')
          pkg_slug=$(echo $PAYLOAD | jq -r '.package_slug // empty')

          if [ -n "$pkg_slug" ]; then
            echo "Tagging package by slug: $pkg_slug"
            cloudsmith tags add "$CS_NAMESPACE/$CS_STAGING_REPO/$pkg_slug" ready-for-production
          elif [ -n "$pkg_name" ] && [ -n "$pkg_version" ]; then
            echo "Searching for $pkg_name@$pkg_version"
            slug=$(cloudsmith ls pkg "$CS_NAMESPACE/$CS_STAGING_REPO" -q "name:${pkg_name} AND version:${pkg_version}" -F json | jq -r '.data[0].slug')
            [ -n "$slug" ] && cloudsmith tags add "$CS_NAMESPACE/$CS_STAGING_REPO/$slug" ready-for-production
          else
            echo "No valid package info in webhook payload"
            exit 1
          fi

      - name: Promote tagged packages to production
        run: |
          echo "Querying for packages with tag: ready-for-production"
          cloudsmith ls pkg "$CS_NAMESPACE/$CS_STAGING_REPO" -q "tag:ready-for-production" -F json \
            | jq -r '.data[] | "\(.namespace)/\(.repository)/\(.slug)"' \
            | while read -r pkg; do
                echo "Promoting $pkg -> $CS_NAMESPACE/$CS_PROD_REPO"
                cloudsmith move "$pkg" "$CS_NAMESPACE/$CS_PROD_REPO"
              done
