name: Release to Cloudsmith (staging)

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types: [completed]

permissions:
  contents: read
  id-token: write  # required for OIDC with Cloudsmith

env:
  CS_NAMESPACE: ${{ secrets.CS_NAMESPACE }}  # e.g. your-org (set as a repo secret)
  CS_STAGING_REPO: "staging"

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist

      - name: Install Cloudsmith CLI (OIDC)
        uses: cloudsmith-io/cloudsmith-cli-action@v1
        with:
          oidc: true

      - name: Push Python package(s) to Cloudsmith staging
        run: |
          shopt -s nullglob
          for pkg in dist/*.whl dist/*.tar.gz; do
            echo "Pushing $pkg"
            cloudsmith push python "${CS_NAMESPACE}/${CS_STAGING_REPO}" "$pkg"
          done
