name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_REPOSITORY: "staging"
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact from build workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_package.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: python-package
          path: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: List directory contents
        run: ls -la dist/
        shell: bash

      - name: Install Cloudsmith CLI
        run: pip install --upgrade cloudsmith-cli

      - name: Push package to Cloudsmith
        env:
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
        echo "Namespace: ${{ env.CLOUDSMITH_NAMESPACE }}"
        echo "Repository: ${{ env.CLOUDSMITH_REPOSITORY }}"
        echo "Files in dist:"
        ls -la dist/
        cloudsmith push python ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPOSITORY }} dist/* --republish
        shell: bash


