name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed

env:
  CLOUDSMITH_NAMESPACE: ${{ secrets.CS_OIDC_NAMESPACE }}
  CLOUDSMITH_REPOSITORY: "staging"
  CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CS_OIDC_SERVICE_SLUG }}

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist

      - name: List directory contents
        run: ls -la dist/
        shell: bash

      - name: Install Cloudsmith CLI
        run: pip install --upgrade cloudsmith-cli

      - name: Push package to Cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          shopt -s nullglob
          for file in dist/*.tar.gz dist/*.whl; do
            echo "Uploading $file ..."
            cloudsmith push python \
              ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPOSITORY }} \
              "$file" --republish
          done
        shell: bash
